name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ngnix-image:latest
    - name: Check for the docker images
      run: docker images
    - name: Check the running docker instance
      run: docker ps -a
    - name: Start docker container
      run: docker run -d -p 80:80 ngnix-image:latest
    - name: Check the running docker instance
      run: docker ps -a
